name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Run workflow on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Allow workflow to write to repository

    steps:
      # Step 1: Checkout code from branch main
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      # Step 3: Install dependencies using npm
      - name: Install dependencies
        run: npm install

      # Step 4: Create .env
      - name: Create .env file
        run: |
          echo "VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}" >> .env
          echo "VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}" >> .env

      # Step 5: Build project
      - name: Build project
        run: npm run build
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

      # Step 6: Create 404 file
      - name: Create 404.html
        run: cp dist/index.html dist/404.html

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
